ISATW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('UserApp.urls', namespace="user_app")),
    url(r'^student/', include('StudentApp.urls', namespace="student_app"))

]

StudentApp/urls.py
from django.conf.urls import url

from StudentApp.views import (
    RegisterStudent,
    ViewStudents,
    ViewStudentsQueryFacuty,
    ViewStudentsQueryScec,
    ViewStudentsQueryAll,
    StudentUpdate,
    delete_student

)

urlpatterns = [
    url(r'^registerStudent', RegisterStudent.as_view(), name='register_student'),
    url(r'^student/edit/(?P<pk>[0-9]+)', StudentUpdate.as_view(), name='edit_student'),
    url(r'^student/delete/(?P<pk>[0-9]+)', delete_student, name='delete_student'),
    url(r'^viewStudents', ViewStudents.as_view(), name='view_students'),
    url(r'^filter/facultate/(?P<facultate_id>\d+)/$', ViewStudentsQueryFacuty.as_view(), name='view_students_f'),
    url(r'^filter/specializare/(?P<specialization_id>\d+)/$', ViewStudentsQueryScec.as_view(), name='view_students_s'),
    url(r'^filter/all/(?P<facultate_id>\d+)/(?P<specialization_id>\d+)/$', ViewStudentsQueryAll.as_view(),
        name='view_students_fs'),
]

StudentApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

GENDER_CHOSE = (
    ("M", "Masculin"),
    ("F", "Feminin")
)


class Facultate(models.Model):
    name = models.CharField(max_length=254, blank=True)

    def __str__(self):
        return self.name

    pass


class Specializare(models.Model):
    name = models.CharField(max_length=254, blank=True)
    facultate = models.ForeignKey(Facultate, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.name

    pass


class Student(models.Model):
    cnp = models.IntegerField(unique=True, editable=True)
    nr_matricol = models.CharField(primary_key=True, unique=True, max_length=254, editable=True)
    first_name = models.CharField(max_length=254, blank=True)
    last_name = models.CharField(max_length=254, blank=True)
    phone = models.CharField(max_length=254, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOSE, blank=True)
    email = models.EmailField(unique=True, blank=True)
    create_at = models.DateTimeField(_('create_at'), default=timezone.now)
    update_at = models.DateTimeField(_('update_at'), default=timezone.now)
    specializations = models.ForeignKey(Specializare, on_delete=models.CASCADE, default=0)
    faculties = models.ForeignKey(Facultate, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.first_name

StudentApp/forms.py
from django import forms
from django.views.generic import UpdateView

from StudentApp.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['create_at', 'update_at']

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StudentFormUpdate(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['create_at', 'update_at', 'cnp', 'nr_matricol']

    def __init__(self, *args, **kwargs):
        super(StudentFormUpdate, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

StudentApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView, DeleteView

from StudentApp.forms import StudentForm, StudentFormUpdate
from StudentApp.models import Facultate
from StudentApp.models import Specializare
from StudentApp.models import Student


# Create your views here.


class RegisterStudent(LoginRequiredMixin, FormView):
    template_name = "register_student.html"
    form_class = StudentForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Student inregistrat cu succes.')
        return redirect('student_app:register_student')


class StudentUpdate(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentFormUpdate
    template_name = "edit_student.html"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Student modificat cu succes.')
        return redirect('student_app:view_students')


class ViewStudents(LoginRequiredMixin, ListView):
    login_url = 'user_app:home'
    template_name = "view_students.html"
    model = Student

    def get_queryset(self):
        search_query = self.request.GET.get('search_box', None)
        facult_filter = self.request.GET.get('nfacts', None)
        spec_filter = self.request.GET.get('sfacts', None)
        query = Student.objects.all()
        facs = Facultate.objects.all()
        specs = Specializare.objects.all()
        if facult_filter:
            query = query.filter(Q(faculties_id=facult_filter)).distinct()
        if spec_filter:
            query = query.filter(Q(specializations_id=spec_filter)).distinct()
        if search_query:
            query = query.filter(Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query) | Q(
                nr_matricol__icontains=search_query)).distinct()
        return {'students': query, 'facs': facs, 'specs': specs}


class ViewStudentsQueryFacuty(ListView):
    template_name = "view_students.html"
    model = Student

    def get_queryset(self):
        query = Student.objects.filter(faculty=self.kwargs['facultate_id'])
        facs = Facultate.objects.all()
        specs = Specializare.objects.all()
        obj = {'students': query, 'facs': facs, 'specs': specs}
        return obj


class ViewStudentsQueryScec(ListView):
    template_name = "view_students.html"
    model = Student

    def get_queryset(self):
        a = self.request.GET
        print(a)

        query = Student.objects.filter(specializations=self.kwargs['specialization_id'])
        facs = Facultate.objects.all()
        specs = Specializare.objects.all()
        obj = {'students': query, 'facs': facs, 'specs': specs}
        return obj


class ViewStudentsQueryAll(ListView):
    template_name = "view_students.html"
    model = Student

    def get_queryset(self):
        query = Student.objects.filter(faculty=self.kwargs['facultate_id'],
                                       specialization=self.kwargs['specialization_id'])
        facs = Facultate.objects.all()
        specs = Specializare.objects.all()
        obj = {'students': query, 'facs': facs, 'specs': specs}
        return obj


def delete_student(request, pk):
    student = get_object_or_404(Student, nr_matricol=pk)
    if student:
        student.delete()
    return redirect('student_app:view_students')

StudentApp/templates/edit_student.html
{% extends "base_logedin_staff.html" %}

{% block content %}
    <!doctype html>
    <html>

    <div class="content-agileits">
        <h1 class="title">Modifica studentul</h1>
        <div class="center">
            <form method="post" enctype="multipart/form-data" data-toggle="validator">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <br>
                <input type="submit" class="btn btn-primary pull-right" value="Save"/>
                <input type="submit" class="btn btn-danger pull-right" style="color:black;"
                       onclick="location.href='{% url 'student_app:view_students' %}';" value="Cancel"/>
            </form>
        </div>
    </div>

    {% load static %}
    <!-- js -->
    <script src="{% static  'js/jquery-2.1.4.min.js ' %}"></script>
    <!-- //js -->

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>

    <!-- /js files -->
{% endblock %}

StudentApp/templates/register_student.html
{% extends "base_logedin_staff.html" %}

{% block content %}
    <!doctype html>
    <html>

    <div class="content-agileits">
        <h1 class="title">Inregistreaza un nou student</h1>
        <div class="center">
            <form method="post" enctype="multipart/form-data" data-toggle="validator">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <input type="submit" class="btn btn-primary pull-right" value="Submit"/>
            </form>
        </div>
    </div>

    {% load static %}
    <!-- js -->
    <script src="{% static  'js/jquery-2.1.4.min.js ' %}"></script>
    <!-- //js -->

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>

    <!-- /js files -->
{% endblock %}

StudentApp/templates/student_confirm_delete.html
{% extends "base_logedin_staff.html" %}

{% block content %}

    <div class="content-agileits">
        <h1 class="title">Stergere student </h1>
        <div class="center">
            <form class="center" style="text-align: center" method="post">{% csrf_token %}
                <h1 class="center">Sunteti sigur ca doriti sa stergeti studentul "{{ object }}"?</h1>
                <br>
                <div class=>
                    <input style="display: block;margin-right: auto;margin-left: auto;" type="submit" value="Confirm"
                           class="btn btn-danger"/>
                    <br>
                    <a style="display: block;margin-right: auto;margin-left: auto;"
                       href='{% url 'student_app:view_students' %}' class="btn btn-primary">Cancel</a>
                </div>
            </form>
        </div>
    </div>

    {% load static %}
    <!-- js -->
    <script src="{% static  'js/jquery-2.1.4.min.js ' %}"></script>
    <!-- //js -->

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>

    <!-- /js files -->
{% endblock %}

StudentApp/templates/view_students.html
{% extends "base_logedin_staff.html" %}

{% block content %}

    <h3 class="title_text">Liste Studenti</h3>

    <div class="content">
        <div>
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <form class="form-inline" type="get" action="{% url 'student_app:view_students' %}" style="margin: 0 ">

                    <div class="dropdown col-sm-2">
                        <label>Facultate</label>
                        <select id="facs" name="nfacts">
                            <option value="">Afiseaza Toate</option>
                            {% for facultate in object_list.facs %}
                                <option value="{{ facultate.id }}">{{ facultate.name }}</option>
                            {% endfor %}
                        </select>

                    </div>


                    <div class="dropdown col-sm-2">
                        <label>Specializare</label>
                        <!--Blue select-->
                        <select id="specs" name="sfacts">
                            <option value="">Afiseaza Toate</option>
                            {% for specs in object_list.specs %}
                                <option value="{{ specs.id }}">{{ specs.name }}</option>
                            {% endfor %}
                        </select>
                        <!--/Blue select-->

                    </div>
                    <div class="col-sm-2">
                        <button class="btn btn-sm" style="color: black" id="search_submit" type="submit">Aplica filtre
                        </button>
                    </div>
                </form>
                <div class="col-sm-2">
                    <button class="btn btn-sm" style="color: black"
                            onclick="location.href='{% url 'student_app:view_students' %}';">Reseteaza filtre
                    </button>
                </div>

                <div class="col-sm-4">
                    <form class="form-inline" type="get" action="{% url 'student_app:view_students' %}"
                          style="margin: 0 ">
                        <center><input id="search_box" type="text" name="search_box"
                                       class="glyphicon glyphicon-search form-control" placeholder=" Cauta...">
                            <button id="search_submits" class="glyphicon glyphicon-search" type="submit"></button>
                        </center>
                    </form>
                </div>

            </div>


            <br>
            <br>
            <div>
                <div>
                    <div class="table-wrapper">
                        <!--Table-->
                        <table class="table">
                            {% if  object_list.students %}
                                <!--Table head-->
                                <thead>
                                <tr>
                                    <th class="th-lg"><strong>Nr matricol</strong></th>
                                    <th class="th-lg"><strong>Nume</strong></th>
                                    <th class="th-lg"><strong>Prenume</strong></th>
                                    <th class="th-lg"><strong>Facultate</strong></th>
                                    <th class="th-lg"><strong>Specializare</strong></th>

                                    <th></th>

                                </tr>

                                </thead>
                                <!--Table head-->
                            {% endif %}
                            <!--Table body-->
                            <tbody>
                            {% for student in object_list.students %}
                                <tr>
                                    <th>{{ student.nr_matricol }}</th>
                                    <th>{{ student.last_name }}</th>
                                    <th>{{ student.first_name }}</th>
                                    <th>{{ student.specializations.facultate }}</th>
                                    <th>{{ student.specializations }}</th>

                                    {% if user.is_authenticated and not user.is_teacher %}
                                        <th>
                                            <button class="btn btn-sm" style="color: black;"
                                                    onclick="window.location.href = '{% url 'student_app:edit_student' student.nr_matricol %}';">
                                                Editeaza
                                            </button>
                                        </th>
                                        <th>
                                        <button class="btn btn-sm btn-danger" data-toggle="modal"
                                                data-target="#myModal{{ student.nr_matricol }}">
                                            Sterge
                                        </button>
                                    {% endif %}

                                </tr>
                                <!--// modal-->
                                <div class="modal fade" id="myModal{{ student.nr_matricol }}" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;
                                                </button>
                                                <h4 class="modal-title">Delete</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Esti sigur ca doresti sa-l stergi?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'student_app:delete_student' student.nr_matricol %}">
                                                    <button type="button" class="btn btn-primary">Sunt sigur
                                                    </button>
                                                </a>
                                                <button type="button" class="btn btn-info" data-dismiss="modal">
                                                    Inchide
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <li>Nu aveti nici o lucrare inregistrata</li>
                            {% endfor %}
                            </tbody>
                            <!--Table body-->
                        </table>
                        <!--Table-->
                    </div>

                    <hr class="my-0">


                </div>
            </div>
        </div>
    </div>

    <style media="screen" type="text/css">
        .content {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            margin-right: 20px !important;
            margin-top: 200px;
            margin-left: 20px !important;

        }

        .title_text {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            width: 100%;
            margin-left: 20px;
            margin-top: 150px;
            right: 0;
        }

    </style>

{% endblock %}