ISATW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('UserApp.urls', namespace="user_app")),
    url(r'^student/', include('StudentApp.urls', namespace="student_app"))

]

ProfessorApp/urls.py
from django.conf.urls import url

from ProfessorApp.views import (
    RegisterProfessor,
    ViewProfessors,
    LucreareView,
    ViewLucrari,
    FileUpload,
    ProfesorUpdate,
    delete_profesor,
    pdf_view,
    UpdateStatusView,
    StatusView,
    delete_status,
    delete_document,
    delete_lucrare,
)

urlpatterns = [
    url(r'^registerProfessor', RegisterProfessor.as_view(), name='register_professor'),
    url(r'^professor/edit/(?P<pk>[0-9]+)', ProfesorUpdate.as_view(), name='edit_professor'),
    url(r'^professor/delete/(?P<pk>[0-9]+)', delete_profesor, name='delete_professor'),
    url(r'^viewProfessors', ViewProfessors.as_view(), name='view_professors'),
    url(r'^registerLucrare', LucreareView.as_view(), name='register_lucrare'),
    url(r'^viewLucrare', ViewLucrari.as_view(), name='view_lucrare'),
    url(r'^fileUpload/(?P<student_id>\d+)/$', FileUpload.as_view(), name='file_upload'),
    url(r'^student/lucrare/view_pdf/(?P<document_id>\d+)/$', pdf_view, name="pdf_view"),
    url(r'^student/lucrare/update_status/(?P<student_id>\d+)/$', UpdateStatusView.as_view(), name="status_update"),
    url(r'^student/lucrare/status/view/(?P<pk>\d+)/$', StatusView.as_view(), name="view_status"),
    url(r'^student/lucrare/status/delete/(?P<pk>[0-9]+)', delete_status, name="delete_status"),
    url(r'^student/lucrare/document/delete/(?P<pk>[0-9]+)', delete_document, name="delete_document"),
    url(r'^student/lucrare/delete/(?P<pk>[0-9]+)', delete_lucrare, name="delete_lucrare"),
]

StudentApp/urls.py
from django.conf.urls import url

from StudentApp.views import (
    RegisterStudent,
    ViewStudents,
    ViewStudentsQueryFacuty,
    ViewStudentsQueryScec,
    ViewStudentsQueryAll,
    StudentUpdate,
    delete_student

)

urlpatterns = [
    url(r'^registerStudent', RegisterStudent.as_view(), name='register_student'),
    url(r'^student/edit/(?P<pk>[0-9]+)', StudentUpdate.as_view(), name='edit_student'),
    url(r'^student/delete/(?P<pk>[0-9]+)', delete_student, name='delete_student'),
    url(r'^viewStudents', ViewStudents.as_view(), name='view_students'),
    url(r'^filter/facultate/(?P<facultate_id>\d+)/$', ViewStudentsQueryFacuty.as_view(), name='view_students_f'),
    url(r'^filter/specializare/(?P<specialization_id>\d+)/$', ViewStudentsQueryScec.as_view(), name='view_students_s'),
    url(r'^filter/all/(?P<facultate_id>\d+)/(?P<specialization_id>\d+)/$', ViewStudentsQueryAll.as_view(),
        name='view_students_fs'),
]

ProfessorApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import FileExtensionValidator
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.db import models

from ProfessorApp.validators import validate_file_extension
from StudentApp.models import Student, Facultate

GENDER_CHOSE = (
    ("M", "Masculin"),
    ("F", "Feminin")
)

LUCRARE_CHOSE = (
    ("L", "Licenta"),
    ("D", "Disertatie")
)


class Professor(models.Model):
    cnp = models.IntegerField(primary_key=True, unique=True, editable=True)
    first_name = models.CharField(max_length=254, blank=True)
    last_name = models.CharField(max_length=254, blank=True)
    phone = models.CharField(max_length=254, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOSE, blank=True)
    email = models.EmailField(unique=True, blank=True)
    create_at = models.DateTimeField(_('create_at'), default=timezone.now)
    update_at = models.DateTimeField(_('update_at'), default=timezone.now)
    faculty = models.ForeignKey(Facultate, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.first_name


class Lucrare(models.Model):
    titluLucrare = models.CharField(max_length=254, blank=True)
    tipLucrare = models.CharField(max_length=1, choices=LUCRARE_CHOSE, blank=True)
    create_at = models.DateTimeField(_('create_at'), default=timezone.now)
    update_at = models.DateTimeField(_('update_at'), default=timezone.now)
    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    profesor = models.ForeignKey(Professor, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.titluLucrare

    def get_full_name(self):
        return self.titluLucrare

    def get_short_name(self):
        return self.titluLucrare


class Document(models.Model):
    descriere = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    este_final = models.BooleanField(default=False)
    create_at = models.DateTimeField(_('create_at'), default=timezone.now)
    update_at = models.DateTimeField(_('update_at'), default=timezone.now)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, default=0)


class LucrareStatus(models.Model):
    description = models.TextField(max_length=10000, blank=True)
    create_at = models.DateTimeField(_('create_at'), default=timezone.now)
    update_at = models.DateTimeField(_('update_at'), default=timezone.now)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, default=0)

ProfessorApp/forms.py
from django import forms

from ProfessorApp.models import Professor, Lucrare, Document, LucrareStatus
from StudentApp.models import Student, Facultate


class ProfessorForm(forms.ModelForm):
    class Meta:
        model = Professor
        fields = '__all__'
        exclude = ['create_at', 'update_at']

    def __init__(self, *args, **kwargs):
        super(ProfessorForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['faculty'].queryset = Facultate.objects.all()


class LucrareForm(forms.ModelForm):
    class Meta:
        model = Lucrare
        fields = '__all__'
        exclude = ['create_at', 'update_at']

    def __init__(self, *args, **kwargs):
        super(LucrareForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StatusForm(forms.ModelForm):
    class Meta:
        model = LucrareStatus
        fields = '__all__'
        exclude = ['create_at', 'update_at', 'student']

    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = '__all__'
        exclude = ['create_at', 'update_at', 'student', 'este_final']

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProfesorFormUpdate(forms.ModelForm):
    class Meta:
        model = Professor
        fields = '__all__'
        exclude = ['create_at', 'update_at', 'cnp']

    def __init__(self, *args, **kwargs):
        super(ProfesorFormUpdate, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

ProfessorApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView, UpdateView, DeleteView, DetailView

from ProfessorApp.forms import ProfessorForm, LucrareForm, ProfesorFormUpdate, DocumentForm, StatusForm
from ProfessorApp.models import Professor, Lucrare, Document, LucrareStatus
from StudentApp.models import Facultate, Student
from UserApp.utils import register_new_teacher, delete_user


class RegisterProfessor(FormView):
    template_name = "register_professor.html"
    form_class = ProfessorForm

    def form_valid(self, form):
        current_site = get_current_site(self.request)
        domain = current_site.domain
        register_new_teacher(form, domain)
        form.save()
        messages.success(self.request, 'Profesor inregistrat cu succes.')
        return redirect('professor_app:register_professor')


class ProfesorUpdate(LoginRequiredMixin, UpdateView):
    model = Professor
    form_class = ProfesorFormUpdate
    template_name = "edit_profesor.html"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Student modificat cu succes.')
        return redirect('professor_app:view_professors')


class ViewProfessors(LoginRequiredMixin, ListView):
    template_name = "view_professors.html"
    model = Professor

    def get_queryset(self):
        search_query = self.request.GET.get('search_box', None)
        facult_filter = self.request.GET.get('nfacts', None)
        query = Professor.objects.all()
        facs = Facultate.objects.all()
        if facult_filter:
            query = query.filter(Q(faculty_id=facult_filter)).distinct()
        if search_query:
            query = query.filter(Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query) | Q(
                cnp__icontains=search_query)).distinct()
        return {'professors': query, 'facs': facs}


class ViewLucrari(LoginRequiredMixin, ListView):
    template_name = "view_lucrari.html"
    model = Lucrare

    def get_queryset(self):
        query = Lucrare.objects.all()
        facs = Facultate.objects.all()
        obj = {'lucarari': query, 'facs': facs}
        return obj


class LucreareView(LoginRequiredMixin, FormView):
    template_name = 'register_lucrare.html'
    form_class = LucrareForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Lucrare inregistrata cu succes.')
        return redirect('professor_app:register_lucrare')


class UpdateStatusView(LoginRequiredMixin, FormView, ListView):
    template_name = 'register_lucrare_status.html'
    form_class = StatusForm

    def form_valid(self, form):
        if self.request.method == 'POST':
            form = StatusForm(self.request.POST)
            if form.is_valid():
                status = form.save(commit=False)
                status.student = Student.objects.get(nr_matricol=self.kwargs['student_id'])
                status.save()

                return redirect(self.request.path_info)

    def get_queryset(self):
        query = LucrareStatus.objects.filter(student_id=self.kwargs['student_id'])
        obj = {'status': query}
        return obj


class StatusView(LoginRequiredMixin, DetailView):
    template_name = 'view_lucrare_status.html'
    model = LucrareStatus

    def get_object(self, queryset=None):
        status = super(StatusView, self).get_object(queryset=queryset)
        return status


class FileUpload(LoginRequiredMixin, FormView, ListView, View):
    template_name = "file_upload.html"
    form_class = DocumentForm
    model = Document

    def form_valid(self, form):
        if self.request.method == 'POST':
            form = DocumentForm(self.request.POST, self.request.FILES)
            if form.is_valid():
                document = form.save(commit=False)
                document.student = Student.objects.get(nr_matricol=self.kwargs['student_id'])
                document.este_final = True if self.request.POST.get('fisier_final') else False
                document.save()

                return redirect(self.request.path_info)

    def get_queryset(self):
        last_item = None
        query = Document.objects.filter(student_id=self.kwargs['student_id'])
        if query:
            last_item = query.reverse().first().este_final
        return {"documents": query, "last": last_item}


def pdf_view(request, *args, **kwargs):
    document = Document.objects.get(id=kwargs['document_id'])
    print(document.descriere)
    print(document.document.url)
    with open(document.document.url, 'r') as pdf:
        print("opened")
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response


def delete_profesor(request, pk):
    profesor = get_object_or_404(Professor, cnp=pk)
    if profesor:
        delete_user(profesor.email)
        profesor.delete()
    return redirect('professor_app:view_professors')


def delete_status(request, pk):
    status = get_object_or_404(LucrareStatus, id=pk)
    if status:
        status.delete()
    return redirect('professor_app:status_update', student_id=status.student.pk)


def delete_document(request, pk):
    document = get_object_or_404(Document, id=pk)
    if document:
        document.delete()
    return redirect('professor_app:file_upload', student_id=document.student.pk)


def delete_lucrare(request, pk):
    lucrare = get_object_or_404(Lucrare, id=pk)
    if lucrare:
        lucrare.delete()
    return redirect('professor_app:view_lucrare')

ProfessorApp/templates/edit_profesor.html
{% extends "base_logedin_staff.html" %}

{% block content %}
    <div class="content-agileits">
        <h1 class="title">Modifica profesor</h1>
        <div class="center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                 {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <br>
                <input type="submit" class="btn btn-primary pull-right" value="Submit"/>
            </form>
        </div>
    </div>

{% endblock %}

ProfessorApp/templates/register_lucrare.html
{% extends "base_logedin_staff.html" %}

{% block content %}
    <div class="content-agileits">
        <h1 class="title">Inregistreaza o noua lucrare</h1>
        <div class="center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <br>
                <input type="submit" class="btn btn-primary pull-right" value="Submit"/>
            </form>
        </div>
    </div>

{% endblock %}

ProfessorApp/templates/register_professor.html
{% extends "base_logedin_staff.html" %}

{% block content %}
    <div class="content-agileits">
        <h1 class="title">Inregistreaza un nou profesor</h1>
        <div class="center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                 {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <br>
                <input type="submit" class="btn btn-primary pull-right" value="Submit"/>
            </form>
        </div>
    </div>

{% endblock %}

ProfessorApp/templates/view_lucrare_status.html
{% extends "base_logedin_staff.html" %}

{% block content %}
    <div class="content-agileits">
        <h1 class="title">Visualizare status</h1>
        <div class="center">
            La data de {{ object.create_at }} s-a inregistrat statusul pentru
            studentul {{ object.student.first_name }} {{ object.student.last_name }}
            <br>
            <br>
            <div class="col-" style="border-style: solid;  border-width: 1px; padding: 10px; height: 200px">
                <p>{{ object.description }}</p>
            </div>
        </div>

        <button class="btn btn-sm" style="color: #000;"
                onclick="window.history.back()">Inapoi
        </button>
    </div>
{% endblock %}

ProfessorApp/templates/view_lucrari.html
{% extends "base_logedin_staff.html" %}

{% block content %}

    <h3 class="title_text ">Liste Lucrari</h3>

    <div class="content">
        <div>
            <br>
            <br>
            <div>
                <div>
                    <div class="table-wrapper">
                        <!--Table-->
                        <table class="table">
                            {% if  object_list.lucarari %}
                                <!--Table head-->
                                <thead>
                                <tr>
                                    <th class="th-lg"><strong>Titlu lucrare</strong></th>
                                    <th class="th-lg"><strong>Tip Lucrare</strong></th>
                                    <th class="th-lg"><strong>Student </strong></th>
                                    <th class="th-lg"><strong>Profesor</strong></th>

                                    <th></th>

                                </tr>

                                </thead>
                            {% endif %}
                            <!--Table head-->

                            <!--Table body-->
                            <tbody>
                            {% for lucarare in object_list.lucarari %}
                                <tr>
                                    <th>{{ lucarare.titluLucrare }}</th>
                                    <th>{{ lucarare.get_tipLucrare_display }}</th>
                                    <th>{{ lucarare.student.first_name }} {{ lucarare.student.last_name }}</th>
                                    <th>{{ lucarare.profesor.first_name }} {{ lucarare.profesor.last_name }}</th>
                                    <th>
                                        <button class="btn btn-sm" style="color: black;"
                                                onclick="window.location.href ='{% url  'professor_app:status_update' lucarare.student.nr_matricol %}'">
                                            Integistreaza status

                                        </button>

                                        <button class="btn btn-sm" style="color: black;"
                                                onclick="window.location.href ='{% url 'professor_app:file_upload' lucarare.student.nr_matricol %}'">
                                            Fisiere
                                        </button>

                                        {% if user.is_authenticated and not user.is_teacher %}
                                            <button class="btn btn-sm btn-danger" data-toggle="modal"
                                                    data-target="#myModal{{ lucarare.id }}">
                                                Sterge
                                            </button>
                                        {% endif %}
                                    </th>
                                </tr>
                                <!--// modal-->
                                <div class="modal fade" id="myModal{{ lucarare.id }}" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;
                                                </button>
                                                <h4 class="modal-title">Delete</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Esti sigur ca doresti sa-l stergi?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'professor_app:delete_lucrare' lucarare.id %}">
                                                    <button type="button" class="btn btn-primary">Sunt sigur
                                                    </button>
                                                </a>
                                                <button type="button" class="btn btn-info" data-dismiss="modal">
                                                    Inchide
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <li>Nu aveti nici o lucrare inregistrata</li>
                            {% endfor %}
                            </tbody>
                            <!--Table body-->
                        </table>
                        <!--Table-->
                    </div>

                    <hr class="my-0">


                </div>
            </div>
        </div>
    </div>

    <style media="screen" type="text/css">
        .content {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            margin-right: 20px !important;
            margin-top: 200px;
            margin-left: 20px !important;

        }

        .title_text {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            width: 100%;
            margin-left: 20px;
            margin-top: 150px;
            right: 0;
        }
    </style>


{% endblock %}

ProfessorApp/templates/view_professors.html
{% extends "base_logedin_staff.html" %}

{% block content %}

    <h3 class="title_text">Liste Profesori</h3>

    <div class="content">
        <div>
            <!--Grid row-->
            <div class="row">
                <form class="form-inline" type="get" action="{% url 'professor_app:view_professors' %}"
                      style="margin: 0 ">
                    <!--Grid column-->
                    <div class="col-sm-2">
                        <label>Facultate</label>
                        <select id="facs" name="nfacts">
                            <option value="">Afiseaza Toate</option>
                            {% for facultate in object_list.facs %}
                                <option value="{{ facultate.id }}">{{ facultate.name }}</option>
                            {% endfor %}
                        </select>

                    </div>

                    <div class="col-sm-2">
                        <button class="btn btn-sm" style="color: black" id="search_submit" type="submit">Aplica filtre
                        </button>
                    </div>
                </form>

                <div class="col-sm-2">
                    <button class="btn btn-sm" style="color: black"
                            onclick="location.href='{% url 'student_app:view_students' %}';">Reseteaza filtre
                    </button>
                </div>

                <!--Grid column-->
                <div class="col-sm-4">
                    <form class="form-inline" type="get" action="{% url 'professor_app:view_professors' %}"
                          style="margin: 0 ">
                        <center><input id="search_box" type="text" name="search_box"
                                       class="glyphicon glyphicon-search form-control" placeholder=" Cauta...">
                            <button id="search_submits" class="glyphicon glyphicon-search" type="submit"></button>
                        </center>
                    </form>
                </div>
                <!--Grid column-->

            </div>


            <br>
            <br>
            <div>
                <div>
                    <div class="table-wrapper">
                        <!--Table-->
                        <table class="table">
                            {% if   object_list.professors %}
                                <!--Table head-->
                                <thead>
                                <tr>
                                    <th class="th-lg"><strong>Cnp</strong></th>
                                    <th class="th-lg"><strong>Nume</strong></th>
                                    <th class="th-lg"><strong>Prenume</strong></th>
                                    <th class="th-lg"><strong>Facultate</strong></th>

                                    <th></th>

                                </tr>

                                </thead>
                                <!--Table head-->
                            {% endif %}
                            <!--Table body-->
                            <tbody>
                            {% for professor in object_list.professors %}
                                <tr>
                                    <th>{{ professor.cnp }}</th>
                                    <th>{{ professor.last_name }}</th>
                                    <th>{{ professor.first_name }}</th>
                                    <th>{{ professor.faculty }}</th>
                                    <th>
                                        <button class="btn btn-sm" style="color: black;"
                                                onclick="window.location.href = '{% url 'professor_app:edit_professor' professor.cnp %}';">
                                            Editeaza
                                        </button>
                                    </th>
                                    <th>
                                        <button class="btn btn-sm btn-danger" data-toggle="modal"
                                                data-target="#myModal{{ professor.cnp }}">
                                            Sterge
                                        </button>
                                </tr>
                                <!--// modal-->
                                <div class="modal fade" id="myModal{{ professor.cnp }}" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;
                                                </button>
                                                <h4 class="modal-title">Delete</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Esti sigur ca doresti sa-l stergi?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'professor_app:delete_professor' professor.cnp %}">
                                                    <button type="button" class="btn btn-primary">Sunt sigur
                                                    </button>
                                                </a>
                                                <button type="button" class="btn btn-info" data-dismiss="modal">
                                                    Inchide
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <li>Nu aveti nici o lucrare inregistrata</li>
                            {% endfor %}
                            </tbody>
                            <!--Table body-->
                        </table>
                        <!--Table-->
                    </div>

                    <hr class="my-0">


                </div>
            </div>
        </div>
    </div>

    <style media="screen" type="text/css">
        .content {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            margin-right: 20px !important;
            margin-top: 200px;
            margin-left: 20px !important;

        }

        .title_text {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            width: 100%;
            margin-left: 20px;
            margin-top: 150px;
            right: 0;
        }


    </style>

{% endblock %}