ISATW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('UserApp.urls', namespace="user_app")),
    url(r'^student/', include('StudentApp.urls', namespace="student_app"))

]

StudentApp/urls.py
from django.conf.urls import url

from StudentApp.views import (
    RegisterStudent,
    ViewStudents,
    ViewStudentsQueryFacuty,
    ViewStudentsQueryScec,
    ViewStudentsQueryAll,
    StudentUpdate,
    delete_student

)

urlpatterns = [
    url(r'^registerStudent', RegisterStudent.as_view(), name='register_student'),
    url(r'^student/edit/(?P<pk>[0-9]+)', StudentUpdate.as_view(), name='edit_student'),
    url(r'^student/delete/(?P<pk>[0-9]+)', delete_student, name='delete_student'),
    url(r'^viewStudents', ViewStudents.as_view(), name='view_students'),
    url(r'^filter/facultate/(?P<facultate_id>\d+)/$', ViewStudentsQueryFacuty.as_view(), name='view_students_f'),
    url(r'^filter/specializare/(?P<specialization_id>\d+)/$', ViewStudentsQueryScec.as_view(), name='view_students_s'),
    url(r'^filter/all/(?P<facultate_id>\d+)/(?P<specialization_id>\d+)/$', ViewStudentsQueryAll.as_view(),
        name='view_students_fs'),
]

UserApp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from UserApp.views import (
    HomePageView,
    change_password
)

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': 'user_app:home'}, name='logout'),
    url(r'^user/change_password/$', change_password, name='change_password'),
    url(r'^$', HomePageView.as_view(), name="home")
]

UserApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_teacher', False)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is staff')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is superuser')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=254, blank=True)
    last_name = models.CharField(max_length=254, blank=True)
    email = models.EmailField(unique=True, blank=True)
    create_at = models.DateTimeField(_('create_at'), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.email

UserApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from UserApp.models import User


class HomePageView(TemplateView, User):
    template_name = 'home.html'


class LoginPageView(TemplateView):
    template_name = 'login.html'


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('user_app:login')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })

UserApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Licente Management</title>{% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
<div class="wrapper">

    {% block content %}
    {% endblock %}


    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Bootstrap Js CDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</div>
</body>
</html>

UserApp/templates/base_logedin.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Licente Management</title>{% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
<div class="wrapper">

    <nav id="sidebar">
        <!-- Sidebar Header -->
        <div id="sidebarCollapse" class="sidebar-header">
            <h3>Licente Mananger</h3>
            <strong>LM</strong>
        </div>

        <!-- Sidebar Links -->
        <ul class="list-unstyled components">
            <li>
                <a href="{% url  'user_app:home' %}">
                    <i class="glyphicon glyphicon-home"></i>
                    Home
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="glyphicon glyphicon-briefcase"></i>
                    About
                </a>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
                    <i class="glyphicon glyphicon-duplicate"></i>
                    Pages
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li><a href="#">Page 1</a></li>
                    <li><a href="#">Page 2</a></li>
                    <li><a href="#">Page 3</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="glyphicon glyphicon-link"></i>
                    Portfolio
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="glyphicon glyphicon-send"></i>
                    Contact
                </a>
            </li>
        </ul>
    </nav>

    {% block content %}
    {% endblock %}


    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Bootstrap Js CDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>
</html>

UserApp/templates/base_logedin_staff.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Licente Management</title>{% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.2/css/mdb.min.css"/>

    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.2/js/mdb.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
`
<body>
<nav id="sidebar">
    <!-- Sidebar Header -->
    <ul class="list-unstyled components">
        <li>
            <a href="{% url  'user_app:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                Acasa
            </a>
        </li>
        {% if user.is_authenticated and not user.is_teacher %}
            <li>
                <a href="{% url  'professor_app:register_professor' %}">
                    <i class="glyphicon glyphicon-send"></i>
                    Inregistreaza profesor
                </a>
            </li>
            <li>
                <a href="{% url  'professor_app:view_professors' %}">
                    <i class="glyphicon glyphicon-send"></i>
                    Vizualizare profesori
                </a>
            </li>
            <li>
                <a href="{% url  'student_app:register_student' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Inregistreaza student
                </a>
            </li>
             <li>
                    <a href="{% url  'student_app:view_students' %}">
                        <i class="glyphicon glyphicon-link"></i>
                        Vizualizare studenti
                    </a>
                </li>
                <li>
                    <a href="{% url  'professor_app:register_lucrare' %}">
                        <i class="glyphicon glyphicon-link"></i>
                        Inregistreaza lucrare
                    </a>
                </li>
                <li>
                    <a href="{% url  'professor_app:view_lucrare' %}">
                        <i class="glyphicon glyphicon-link"></i>
                        Vizualizare lucrare
                    </a>
                </li>
                <br>
                <li>
                     <a href="{% url  'user_app:change_password' %}">
                        <i class="glyphicon glyphicon-lock"></i>
                        Schimbare parola
                    </a>
                </li>
                <li>

                    <a href="{% url  'user_app:logout' %}">
                        <i class="glyphicon glyphicon-log-out"></i>
                        Log out
                    </a>
                </li>
         {% elif user.is_authenticated and user.is_teacher %}
            <li>
                <a href="{% url  'student_app:view_students' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Vizualizare studenti
                </a>
            </li>
            <li>
                <a href="{% url  'professor_app:register_lucrare' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Inregistreaza lucrare
                </a>
            </li>
            <li>
                <a href="{% url  'professor_app:view_lucrare' %}">
                    <i class="glyphicon glyphicon-link"></i>
                    Vizualizare lucrare
                </a>
            </li>
            <br>
            <li>
                 <a href="{% url  'user_app:change_password' %}">
                    <i class="glyphicon glyphicon-lock"></i>
                   Schimbare parola

                </a>
            </li>
            <li>

                <a href="{% url  'user_app:logout' %}">
                    <i class="glyphicon glyphicon-log-out"></i>
                    Log out
                </a>
            </li>

        {% else %}
            <li>
                <a href="{% url  'user_app:login' %}">
                    <i class="glyphicon glyphicon-log-in"></i>
                    Log in
                </a>
            </li>
        {% endif %}
    </ul>

    <!-- Sidebar Links -->
    <div id="sidebarCollapse" class="sidebar-header">
        <h3>Licente Mananager</h3>
        <strong>LM</strong>
    </div>
</nav>
<div class="wrapper">

    <div id="content-area" style="width: 100%; background-color: #fff;">
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<!-- Bootstrap Js CDN -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</body>
</html>

UserApp/templates/change_password.html
{% extends "base_logedin_staff.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="col-md-12 ">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="about-agileits-title">
                    <h3>Change Password</h3>
                </div>
            </div>
            <div class="panel-body">
                <div class="box box-info">
                    <div class="box-body">
                        <div class="col-xs-6 col-md-offset-3 ">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {% for field in form %}
                                    <div class="input-group">
                                        <span class="input-group-addon"
                                              style="background-color:#ff5500; color:white"><span
                                                class="glyphicon glyphicon-lock"></span></span>
                                        <input class="form-control" id="{{ field.id_for_label }}" maxlength="30"
                                               name="{{ field.html_name }}" placeholder="{{ field.label }}"
                                               type="password" required/>
                                    </div>
                                    <br>
                                    {% endfor %}

                                    {% if form.errors %}
                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                    {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                    {% endfor %}
                                    {% endif %}
                                    <input type="submit" class="btn btn-primary btn-block" value="Salvare"/>
                                    <input type="hidden" name="next" value="{{ next }}"/>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

UserApp/templates/home.html
{% extends "base_logedin_staff.html" %}

{% block content %}

    <div class="content-agileits">
        <h1 class="title">Bun venit</h1><br>
        {% load static %}

        <img src="{% static "images/usv_logo.png" %}" alt="My image" height="250" width="800"/>


        <div class="center">
            {% if user.is_authenticated %}
                <p>Welcome home, {{ user.get_full_name }}. Thanks for logging in. Last login: {{ user.last_login }}</p>
            {% else %}
                <p>Welcome home, new user. Please log in.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

UserApp/templates/login.html
{% extends "base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">

{% block content %}
    <div class="main" style="display: flex; background: white; position: relative; width: 100%">
        <div class="wrapper_home" style="display: flex">
            {% load static %}
            <img src="{% static "images/usv_logo.png" %}" alt="My image" height="250" width="800"
                 style="position: absolute; left: 0; right: 0; margin: 100px auto auto;"/>
            <form action="{% url 'user_app:login' %}" method="post" name="Login_Form"

                  class="form-signin" style="margin: 30% auto auto; width: 50%"
                  autocomplete="off">
                {% csrf_token %}
                <h3 class="form-signin-heading" style="text-align: center">Welcome! Please Sign In</h3>

                <div class="form-group">
                    {% for field in form %}
                        <div class="input-group">
                            {% if field.label == 'Email' %}
                                <span class="input-group-addon" style="background-color:blue; color:white"><span
                                        class="glyphicon glyphicon-user"></span></span>
                            {% else %}
                                <span class="input-group-addon" style="background-color:blue; color:white"><span
                                        class="glyphicon glyphicon-lock"></span></span>
                            {% endif %}
                            <input class="form-control"
                                   id="{{ field.id_for_label }}"
                                   maxlength="30"
                                   name="{{ field.html_name }}"
                                   placeholder="{{ field.label }}"
                                   type="{{ field.label }}"
                                   required
                            />
                        </div>
                        <br>
                    {% endfor %}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <button class="btn btn-lg btn-primary btn-block" name="Submit" value="Login" type="Submit">Login
                </button>
            </form>
        </div>
    </div>

{% endblock %}